rootProject.name = "Training diary"
include(":app")
include(":core:coroutine")
include(":core:mvi")
include(":external:storage")
include(":features:muscle_groups:api")
include(":features:muscle_groups:impl")
include(":features:training:api")
include(":features:training:impl")
include(":features:exercise_name:api")
include(":features:exercise_name:impl")
include(":external:preferences")
include(":features:approach:api")
include(":features:approach:impl")
include(":features:exercise:api")
include(":features:exercise:impl")
include(":features:super_set:api")
include(":features:super_set:impl")
