rootProject.name = "Training diary"
include(":app")
include(":core:coroutine")
include(":core:mvi")
include(":external:storage:api")
include(":external:storage:impl")
include(":domain:api")
include(":domain:impl")
include(":external:repositories")
include(":features:muscle_groups:api")
include(":features:muscle_groups:impl")
include(":features:training:api")
include(":features:training:impl")
